steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/test-shared-pkim/pkim-images/service-opt-cloud-run:$SHORT_SHA"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/test-shared-pkim/pkim-images/service-opt-cloud-run:$SHORT_SHA"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "service-opt-cloud-run"
      - "--image=us-central1-docker.pkg.dev/test-shared-pkim/pkim-images/service-opt-cloud-run:$SHORT_SHA"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"
images:
  - "us-central1-docker.pkg.dev/test-shared-pkim/pkim-images/service-opt-cloud-run:$SHORT_SHA"
options:
  logging: CLOUD_LOGGING_ONLY  # Or your preferred logging option
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET # Or your bucket option
  #runWith:
  #  serviceAccount: "projects/test-shared-pkim/serviceAccounts/svc-pkim@test-shared-pkim.iam.gserviceaccount.com"